### ISSUE TITLE
Ubuntu 22.04.1 LTS Collector not working

### ISSUE THREAD

**Issue by j1nka** [stackrox/collector#907]
Hi!

I'm trying to run StackRox on `22.04.1 LTS (Jammy Jellyfish)` with Kernel `Linux 5.15.0-52-generic x86_64`. This Kernel is supported according to KERNEL_VERSIONS.

Looks like Collector starts normally (I use `quay.io/stackrox-io/collector-slim:3.72.1`):

```
Collector Version: 3.11.1
OS: Ubuntu 22.04.1 LTS
Kernel Version: 5.15.0-52-generic
Starting StackRox Collector...
[I 20221118 071354 HostInfo.cpp:126] Hostname: 'dsworker2'
[I 20221118 071354 CollectorConfig.cpp:149] User configured collection-method=ebpf
[I 20221118 071354 CollectorConfig.cpp:206] Afterglow is enabled
[I 20221118 071354 collector.cpp:302] Module version: 2.1.0
[I 20221118 071354 collector.cpp:329] Attempting to download eBPF probe - Candidate kernel versions:
[I 20221118 071354 collector.cpp:331] 5.15.0-52-generic
[I 20221118 071354 GetKernelObject.cpp:180] Local storage does not contain collector-ebpf-5.15.0-52-generic.o
[I 20221118 071354 GetKernelObject.cpp:194] Successfully downloaded and decompressed /module/collector-ebpf.o
[I 20221118 071354 collector.cpp:262]
[I 20221118 071354 collector.cpp:263] This product uses kernel module and ebpf subcomponents licensed under the GNU
[I 20221118 071354 collector.cpp:264] GENERAL PURPOSE LICENSE Version 2 outlined in the /kernel-modules/LICENSE file.
[I 20221118 071354 collector.cpp:265] Source code for the kernel module and ebpf subcomponents is available upon
[I 20221118 071354 collector.cpp:266] request by contacting support@stackrox.com.
[I 20221118 071354 collector.cpp:267]
[I 20221118 071354 collector.cpp:215] gRPC server=sensor.stackrox.svc:443
[I 20221118 071354 CollectorService.cpp:50] Config: collection_method:ebpf, useChiselCache:1, snapLen:0, scrape_interval:30, turn_off_scrape:0, hostname:dsworker2, logLevel:INFO
[I 20221118 071354 CollectorService.cpp:79] Network scrape interval set to 30 seconds
[I 20221118 071354 CollectorService.cpp:82] Waiting for GRPC server to become ready ...
[I 20221118 071354 CollectorService.cpp:87] GRPC server connectivity is successful
[I 20221118 071354 NetworkStatusNotifier.cpp:168] Started network status notifier.
[I 20221118 071354 NetworkStatusNotifier.cpp:182] Established network connection info stream.
[I 20221118 071354 SignalServiceClient.cpp:43] Trying to establish GRPC stream for signals ...
[I 20221118 071354 SignalServiceClient.cpp:61] Successfully established GRPC stream for signals.
```
And that's it. In StackRox console I can see only this message: "No processes discovered. The selected deployment may not have running pods, or Collector may not be running in your cluster. It is recommended to check the logs for more information". Nothing happens.

And if I will check "System Health" status - everything is "green". Maybe you have some ideas what am I doing wrong? Thanks in advance!!!

**Comment by Molter73** [comment]
Hi @j1nka, I just run some tests on that same kernel locally and collector seems to be working as intended. I'll look deeper to see if I find anything out of the ordinary, but I've had a similar issue not so long ago were sensor running on kubernetes 1.25 was failing to get information about the running containers from the kubernetes API. Could you double check your kubernetes version and look into the sensor logs?

**Comment by Molter73** [comment]
Could you try setting sensor logging to debug mode by adding the following environment variable?
```yaml
        env:
        - name: LOGLEVEL
          value: Debug
```

Then look for a log such as this one after a while:
```
common/networkflow/manager: 2022/11/18 11:18:34.343378 manager_impl.go:437: Debug: Unable to fetch deployment information for container 867d39b9c0cc: no deployment found
```

I'm looking into what might be the issue, but if this is something you are encountering, we might need to involve someone in the main repo with more experience in sensor.

**Comment by j1nka** [comment]
Thanks! Yes, all is like you mentioned above:

```
pkg/metrics: 2022/11/18 12:09:44.636326 throttle.go:51: Debug: error reading file /sys/fs/cgroup/cpu/cpu.stat: open /sys/fs/cgroup/cpu/cpu.stat: no such file or directory
pkg/metrics: 2022/11/18 12:10:14.636390 throttle.go:51: Debug: error reading file /sys/fs/cgroup/cpu/cpu.stat: open /sys/fs/cgroup/cpu/cpu.stat: no such file or directory
common/networkflow/manager: 2022/11/18 12:10:14.654785 manager_impl.go:259: Debug: Unable to fetch deployment information for container 53a5bedded27: no deployment found
common/networkflow/manager: 2022/11/18 12:10:14.654908 manager_impl.go:259: Debug: Unable to fetch deployment information for container bd2de1fefbef: no deployment found
common/networkflow/manager: 2022/11/18 12:10:14.654928 manager_impl.go:259: Debug: Unable to fetch deployment information for container 53a5bedded27: no deployment found
common/networkflow/manager: 2022/11/18 12:10:14.654946 manager_impl.go:259: Debug: Unable to fetch deployment information for container 90a26911cbd5: no deployment found
common/networkflow/manager: 2022/11/18 12:10:14.654954 manager_impl.go:259: Debug: Unable to fetch deployment information for container 5c8a6eae333c: no deployment found
```

**Comment by Molter73** [comment]
Alright, I think I found it. Turns out the `v1beta1.CronJob` that is being alerted as not found has been removed in version 1.25 of kubernetes: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#cronjob-v125

Making the following change to sensor seems to fix the issue:
```diff
diff --git a/sensor/kubernetes/listener/resource_event_handler.go b/sensor/kubernetes/listener/resource_event_handler.go
index 1a5a63bfa8..02d7a169ff 100644
--- a/sensor/kubernetes/listener/resource_event_handler.go
+++ b/sensor/kubernetes/listener/resource_event_handler.go
@@ -202,7 +202,7 @@ func (k *listenerImpl) handleAllEvents() {
        handle(resyncingSif.Apps().V1().DaemonSets().Informer(), dispatchers.ForDeployments(kubernetes.DaemonSet), k.outputQueue, &syncingResources, wg, stopSignal, &eventLock)
        handle(resyncingSif.Apps().V1().Deployments().Informer(), dispatchers.ForDeployments(kubernetes.Deployment), k.outputQueue, &syncingResources, wg, stopSignal, &eventLock)
        handle(resyncingSif.Apps().V1().StatefulSets().Informer(), dispatchers.ForDeployments(kubernetes.StatefulSet), k.outputQueue, &syncingResources, wg, stopSignal, &eventLock)
-       handle(resyncingSif.Batch().V1beta1().CronJobs().Informer(), dispatchers.ForDeployments(kubernetes.CronJob), k.outputQueue, &syncingResources, wg, stopSignal, &eventLock)
+       handle(resyncingSif.Batch().V1().CronJobs().Informer(), dispatchers.ForDeployments(kubernetes.CronJob), k.outputQueue, &syncingResources, wg, stopSignal, &eventLock)
```

I will ask around with the broader team about this, see if I can submit the patch directly or if someone else is already working on this. In the meantime I see two possibilities for you:
- If downgrading kubernetes to v1.24, that should directly fix the issue.
- You can build a custom version of the main image with the change I provided and configure sensor to run using that instead. (see [this](https://github.com/stackrox/stackrox/blob/772ffd9ff59a7b684a8fee2387090e501d51263d/README.md?plain=1#L349) for instructions on how to build your own image).

**Comment by j1nka** [comment]
@Molter73 thanks a million!!! Will do it and give you feedback.

**Comment by j1nka** [comment]
@Molter73 hi! 

As you suggested I've build another main images with `handle(resyncingSif.Batch().V1().CronJobs().Informer(), dispatchers.ForDeployments(kubernetes.CronJob), k.outputQueue, &syncingResources, wg, stopSignal, &eventLock)` and got the following error:

```
E1121 06:26:52.428725       1 runtime.go:79] Observed a panic: spec obj {Schedule:0 0 * * * TimeZone:<nil> StartingDeadlineSeconds:<nil> ConcurrencyPolicy:Allow Suspend:0xc00284fc75 JobTemplate:{ lot's of data aboy job spec according to it's structure } does not have a Template field)
goroutine 479 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x2d73aa0?, 0xc001d4e5b8})
        k8s.io/apimachinery@v0.24.6/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x203000?})
        k8s.io/apimachinery@v0.24.6/pkg/util/runtime/runtime.go:49 +0x75
panic({0x2d73aa0, 0xc001d4e5b8})
        runtime/panic.go:838 +0x207
github.com/stackrox/rox/pkg/utils.hardPanic({0x2d73aa0?, 0xc001d4e5b8})
        github.com/stackrox/rox/pkg/utils/must.go:25 +0xb6
github.com/stackrox/rox/pkg/utils.ShouldErr(...)
        github.com/stackrox/rox/pkg/utils/must.go:51
github.com/stackrox/rox/pkg/utils.Should(...)
        github.com/stackrox/rox/pkg/utils/must.go:61
github.com/stackrox/rox/sensor/kubernetes/listener/resources.newDeploymentEventFromResource({0x309bce0, 0xc000ded000}, 0xc0039c3930?, {0x30df200?, 0x8000000000000000?}, {0xc0018ff260?, 0x0?}, {0x37d4fd8, 0xc0007c3f30}, 0xc0013a1740, ...)
        github.com/stackrox/rox/sensor/kubernetes/listener/resources/convert.go:88 +0x145
github.com/stackrox/rox/sensor/kubernetes/listener/resources.(*deploymentHandler).processWithType(0xc000eca160, {0x309bce0?, 0xc000ded000}, {0x0, 0x0}, 0x4, {0x30df200, 0x7})
        github.com/stackrox/rox/sensor/kubernetes/listener/resources/deployments.go:120 +0x126
github.com/stackrox/rox/sensor/kubernetes/listener/resources.(*deploymentDispatcherImpl).ProcessEvent(0xc00147d0c8, {0x309bce0, 0xc000ded000}, {0x0, 0x0}, 0x4)
        github.com/stackrox/rox/sensor/kubernetes/listener/resources/deployments.go:63 +0x135
github.com/stackrox/rox/sensor/kubernetes/listener/resources.metricDispatcher.ProcessEvent({{0x37c1980?, 0xc00147d0c8?}}, {0x309bce0, 0xc000ded000}, {0x0, 0x0}, 0xffffffff?)
        github.com/stackrox/rox/sensor/kubernetes/listener/resources/dispatcher.go:203 +0x153
github.com/stackrox/rox/sensor/kubernetes/listener.(*resourceEventHandlerImpl).sendResourceEvent(0xc000b203f0, {0x309bce0, 0xc000ded000}, {0x0, 0x0}, 0x1?)
        github.com/stackrox/rox/sensor/kubernetes/listener/resource_event_handler_impl.go:108 +0x7c
github.com/stackrox/rox/sensor/kubernetes/listener.(*resourceEventHandlerImpl).OnAdd(0xc000b203f0, {0x309bce0, 0xc000ded000})
        github.com/stackrox/rox/sensor/kubernetes/listener/resource_event_handler_impl.go:35 +0x45
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
        k8s.io/client-go@v0.24.6/tools/cache/shared_informer.go:818 +0xaf
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x0?)
        k8s.io/apimachinery@v0.24.6/pkg/util/wait/wait.go:155 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0012f7f38?, {0x37c3700, 0xc0013889f0}, 0x1, 0xc001bb8360)
        k8s.io/apimachinery@v0.24.6/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x3b9aca00, 0x0, 0x31?, 0xc0012f7f88?)
        k8s.io/apimachinery@v0.24.6/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
        k8s.io/apimachinery@v0.24.6/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc0020dea80?)
        k8s.io/client-go@v0.24.6/tools/cache/shared_informer.go:812 +0x6b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
        k8s.io/apimachinery@v0.24.6/pkg/util/wait/wait.go:73 +0x5a
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        k8s.io/apimachinery@v0.24.6/pkg/util/wait/wait.go:71 +0x85
```
Maybe my build is not correct, don't know. To test it I build image again with "original" call - `handle(resyncingSif.Batch().V1beta1().CronJobs().Informer(), dispatchers.ForDeployments(kubernetes.CronJob), k.outputQueue, &syncingResources, wg, stopSignal, &eventLock)` and yes, the same error like in this topic - `Unable to fetch deployment information for container`

**Comment by j1nka** [comment]
Hmmm. Changed `sensor\kubernetes\listener\resources`:
```
- case *v1beta1.CronJob
+ case *batch.CronJob:
		// Cron jobs have a Job spec that then have a Pod Template underneath
		podLabels = o.Spec.JobTemplate.Spec.Template.GetLabels()
		podSpec = o.Spec.JobTemplate.Spec.Template.Spec
                ...
```

Where `batch` is `batch "k8s.io/api/batch/v1"`. And now it's working for processes and networking. Don't know about all other functions :)

**Comment by Molter73** [comment]
Hi @j1nka, just finished testing [a similar change](https://github.com/stackrox/stackrox/pull/3854/commits/3d93bd218fe5e036da0f04094e967cdda2f7a5ce) and this seems to fix it, I should've tested with at least one cronjob in my cluster, that was a terrible judgement error on my side, sorry!
